source 'https://rubygems.org'
gem 'rails', '3.2.12'
gem 'mysql2'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'cancan'
gem 'mysql2'
gem 'therubyracer'
gem 'less-rails'
gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '~> 3.2.1'
gem 'uglifier', '>= 1.0.3'
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
gem 'jquery-ui-rails'
gem 'jquery-rails'
gem 'twitter-bootstrap-rails'
gem 'bootstrap-will_paginate'
gem 'will_paginate', '~> 3.0.2'
gem 'thin'
gem 'foreman'
# ??? do we need these:
gem 'rabl'
gem "active_model_serializers", "~> 0.7.0"
